<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="INHYD-GF401B3" failures="0" tests="2" name="src.NewTest" time="251.286" errors="2" timestamp="2022-04-29T18:35:13 IST" skipped="0">
  <testcase classname="src.NewTest" name="CelticCionsJackpot" time="208.244">
    <error message="C:/Users/pdf57170/Desktop/sekuliImages/Kentucky/CelticCoinsJackpot/home7.png: (56x50) seen at (1093, 149) with 1.00 in S(0)[0,0 1360x768] E:Y, T:3.0" type="org.sikuli.script.FindFailed">
      <![CDATA[FindFailed: C:/Users/pdf57170/Desktop/sekuliImages/Kentucky/CelticCoinsJackpot/home7.png: (56x50) seen at (1093, 149) with 1.00 in S(0)[0,0 1360x768] E:Y, T:3.0
  Line 2761, in file Region.java

at org.sikuli.script.Region.wait(Region.java:2761)
at org.sikuli.script.Region.find(Region.java:2326)
at org.sikuli.script.Region.getLocationFromTarget(Region.java:3220)
at org.sikuli.script.Region.click(Region.java:3718)
at org.sikuli.script.Region.click(Region.java:3703)
at src.NewTest.CelticCionsJackpot(NewTest.java:92)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- CelticCionsJackpot -->
  <system-out/>
  <testcase classname="src.NewTest" name="quickPlay" time="43.042">
    <error message="C:/Users/pdf57170/Desktop/sekuliImages/Kentucky/quickPlay/home6.png: (53x56) seen at (1094, 148) with 0.92 in S(0)[0,0 1360x768] E:Y, T:3.0" type="org.sikuli.script.FindFailed">
      <![CDATA[FindFailed: C:/Users/pdf57170/Desktop/sekuliImages/Kentucky/quickPlay/home6.png: (53x56) seen at (1094, 148) with 0.92 in S(0)[0,0 1360x768] E:Y, T:3.0
  Line 2761, in file Region.java

at org.sikuli.script.Region.wait(Region.java:2761)
at org.sikuli.script.Region.find(Region.java:2326)
at org.sikuli.script.Region.getLocationFromTarget(Region.java:3220)
at org.sikuli.script.Region.click(Region.java:3718)
at org.sikuli.script.Region.click(Region.java:3703)
at src.NewTest.quickPlay(NewTest.java:61)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- quickPlay -->
  <system-out/>
</testsuite> <!-- src.NewTest -->
